name: spake2
version: 0.4.0
synopsis: Implementation of the SPAKE2 Password-Authenticated Key Exchange algorithm
description: |
  This library implements the SPAKE2 password-authenticated key exchange
  ("PAKE") algorithm. This allows two parties, who share a weak password, to
  safely derive a strong shared secret (and therefore build an
  encrypted+authenticated channel).
maintainer: Jonathan M. Lange <jml@mumak.net>
license: Apache
github: jml/haskell-spake2
category: Crypto
extra-source-files:
  - CHANGELOG.md

ghc-options: -Wall -Wno-type-defaults
default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings

dependencies:
  - base >= 4.9 && < 5
  - protolude >= 0.3

executables:
  haskell-spake2-interop-entrypoint:
    main: Main.hs
    ghc-options: -threaded
    source-dirs: cmd/interop-entrypoint
    dependencies:
      - cryptonite
      - memory
      - optparse-applicative
      - spake2

library:
  source-dirs: src
  dependencies:
    - bytestring
    - cryptonite
    - memory

tests:
  tasty:
    main: Tasty.hs
    source-dirs: tests
    dependencies:
      - aeson
      - bytestring
      - cryptonite
      - memory
      - process
      - QuickCheck
      - spake2
      - tasty
      - tasty-hspec

# Only used for testing.
data-files:
  - tests/python/spake2_exchange.py
