version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - run:
          name: Install Dependencies
          command: |
            apt-get update
            apt-get install -y cabal-install

      - checkout

      - run:
          name: Install pip
          command: apt-get install -y python3-pip

      - run:
          name: Install dependencies
          command: pip3 install --user -r requirements.txt

      - run:
          name: upgrade Cabal
          command: |
            cabal update
            cabal install cabal-install

      - run:
          name: Tests
          command: |
            cabal configure --enable-tests
            cabal test
