version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - stack-ghc-{{ checksum "stack.yaml" }}
      - restore_cache:
          keys:
            - stack-deps-{{ checksum "package.yaml" }}
      - run:
          name: Set up Stack
          command: stack setup --no-terminal --no-reinstall
      - save_cache:
          key: stack-ghc-{{ checksum "stack.yaml" }}
          paths:
            - /root/.stack
      - run:
          name: Install dependencies
          command: stack build --skip-ghc-check --no-terminal --test --only-dependencies
      - save_cache:
          key: stack-deps-{{ checksum "package.yaml" }}
          paths:
            - /root/.stack
            - .stack-work
      - run:
          name: apt-get update
          command: apt-get update
      - run:
          name: Install pip
          command: apt-get install -y python-pip
      - run:
          name: Install dependencies
          command: pip install --user -r requirements.txt
      - run:
          name: Tests
          command: stack test --skip-ghc-check --no-terminal
